graphql:
    servlet:
        enabled: true
        exception-handlers-enabled: true
token:
    header-name: "Authorization"
    prefix: "Bearer "
    secret-password: "Mario bross!"
    duration-ms: 3600000